// Generate scripts/seed.sql for local dev: a clean slate with a working login and the built-in
// system account — and deliberately NO benchmarks. Creating a benchmark (draft → ready → publish →
// ingest keys → beacons) is exactly the flow to exercise by hand through the console/API, so the
// seed never fabricates one on anyone's behalf. Ingested reference data comes from the importer
// (`node ingestion/import.mjs`), never from this seed.
//
//   node scripts/gen-seed.mjs > scripts/seed.sql
//
// Dev credentials (LOCAL ONLY — never real): login dev@smplkit.test / smplmark-dev-password.

import { webcrypto as crypto } from "node:crypto";

const DEV_PASSWORD = "smplmark-dev-password";
const enc = new TextEncoder();

const b64url = (bytes) => Buffer.from(bytes).toString("base64url");

async function hashPassword(password) {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const km = await crypto.subtle.importKey("raw", enc.encode(password), "PBKDF2", false, ["deriveBits"]);
  const bits = await crypto.subtle.deriveBits({ name: "PBKDF2", salt, iterations: 210_000, hash: "SHA-256" }, km, 256);
  return `pbkdf2$sha256$210000$${b64url(salt)}$${b64url(new Uint8Array(bits))}`;
}

const q = (s) => (s === null || s === undefined ? "NULL" : `'${String(s).replace(/'/g, "''")}'`);
const uuid = () => crypto.randomUUID();

const T0 = Date.UTC(2026, 6, 1, 0, 0, 0); // seed epoch
const userId = "usr-dev";
const acctId = "acct-smplkit";

const passwordHash = await hashPassword(DEV_PASSWORD);

const out = `-- smplmark local dev seed (generated by scripts/gen-seed.mjs — do not edit by hand).
-- Apply: wrangler d1 execute smplmark --local --file scripts/seed.sql
--
-- DEV CREDENTIALS (local only — never real):
--   Web login:  dev@smplkit.test  /  ${DEV_PASSWORD}
--
-- No benchmarks are seeded — create them through the console (that IS the product test drive).
-- Ingested reference data: node ingestion/import.mjs

DELETE FROM observation; DELETE FROM run; DELETE FROM target;
DELETE FROM benchmark_tag; DELETE FROM tag; DELETE FROM benchmark_view_day; DELETE FROM benchmark;
DELETE FROM api_key; DELETE FROM email_verification; DELETE FROM session;
DELETE FROM account_user; DELETE FROM account; DELETE FROM user_identity; DELETE FROM user;

INSERT INTO user (id, email, email_verified, display_name, created_at) VALUES
  (${q(userId)}, 'dev@smplkit.test', 1, 'smplkit dev', ${T0});
INSERT INTO user_identity (id, user_id, provider, provider_subject, password_hash, created_at) VALUES
  (${q(uuid())}, ${q(userId)}, 'PASSWORD', NULL, ${q(passwordHash)}, ${T0});

-- The built-in system account (0004 seeds it in prod; the wipe above removes it, so re-create it).
INSERT INTO account (id, key, name, description, url, created_at, allow_personal_publish) VALUES
  ('acct-system', 'system', 'smplmark', 'Openly licensed benchmark results ingested from third-party sources. Every ingested benchmark credits its source and license, and links back to the original data.', NULL, ${T0}, 0);

-- The dev workspace: personal publish pre-enabled so the whole publish flow is exercisable.
INSERT INTO account (id, key, name, description, url, created_at, allow_personal_publish) VALUES
  (${q(acctId)}, 'smplkit', 'smplkit', 'smplkit builds developer infrastructure — configuration, feature flags, logging, and audit as independently deployable services.', 'https://smplkit.com', ${T0}, 1);
INSERT INTO account_user (account_id, user_id, role, created_at) VALUES
  (${q(acctId)}, ${q(userId)}, 'OWNER', ${T0});
`;

process.stdout.write(out);
