-- smplmark local dev seed (generated by scripts/gen-seed.mjs — do not edit by hand).
-- Apply: wrangler d1 execute smplmark --local --file scripts/seed.sql
--
-- DEV CREDENTIALS (local only — never real):
--   Web login:  dev@smplkit.test  /  smplmark-dev-password
--
-- No benchmarks are seeded — create them through the console (that IS the product test drive).
-- Ingested reference data: node ingestion/import.mjs

DELETE FROM observation; DELETE FROM run; DELETE FROM target;
DELETE FROM benchmark_tag; DELETE FROM tag; DELETE FROM benchmark_view_day; DELETE FROM benchmark;
DELETE FROM api_key; DELETE FROM email_verification; DELETE FROM session;
DELETE FROM account_user; DELETE FROM account; DELETE FROM user_identity; DELETE FROM user;

INSERT INTO user (id, email, email_verified, display_name, created_at) VALUES
  ('usr-dev', 'dev@smplkit.test', 1, 'smplkit dev', 1782864000000);
INSERT INTO user_identity (id, user_id, provider, provider_subject, password_hash, created_at) VALUES
  ('a5bafeb0-4c2c-459e-85de-a1622feeb7c0', 'usr-dev', 'PASSWORD', NULL, 'pbkdf2$sha256$210000$AJlCOUvN05vgG_-rEYUSaA$skgbZ_QR4e-bUcfFG5DTYF-a1tiPTfLMGMlJD8XCD_c', 1782864000000);

-- The built-in system account (0004 seeds it in prod; the wipe above removes it, so re-create it).
INSERT INTO account (id, key, name, description, url, created_at, allow_personal_publish) VALUES
  ('acct-system', 'system', 'smplmark', 'Openly licensed benchmark results ingested from third-party sources. Every ingested benchmark credits its source and license, and links back to the original data.', NULL, 1782864000000, 0);

-- The dev workspace: personal publish pre-enabled so the whole publish flow is exercisable.
INSERT INTO account (id, key, name, description, url, created_at, allow_personal_publish) VALUES
  ('acct-smplkit', 'smplkit', 'smplkit', 'smplkit builds developer infrastructure — configuration, feature flags, logging, and audit as independently deployable services.', 'https://smplkit.com', 1782864000000, 1);
INSERT INTO account_user (account_id, user_id, role, created_at) VALUES
  ('acct-smplkit', 'usr-dev', 'OWNER', 1782864000000);
