-- smplmark local dev seed (generated by scripts/gen-seed.mjs — do not edit by hand).
-- Apply: wrangler d1 execute smplmark --local --file scripts/seed.sql
--
-- DEV CREDENTIALS (local only — never real):
--   Web login:  dev@smplkit.test  /  smplmark-dev-password
--
-- No benchmarks are seeded — create them through the console (that IS the product test drive).
-- Ingested reference data: node ingestion/import.mjs

-- Wipe every data table (children before parents so foreign keys stay satisfied). All ingested
-- reference data — benchmarks, subjects, metrics, sources, publishers — is intentionally cleared;
-- the importer (node ingestion/import.mjs) repopulates it. The seed only re-creates login + accounts.
DELETE FROM measurement; DELETE FROM run;
DELETE FROM benchmark_metric; DELETE FROM benchmark_subject; DELETE FROM benchmark_tag;
DELETE FROM benchmark_view_day; DELETE FROM takedown_request; DELETE FROM benchmark;
DELETE FROM subject; DELETE FROM metric; DELETE FROM tag; DELETE FROM subject_type;
DELETE FROM external_source; DELETE FROM publisher;
DELETE FROM api_key; DELETE FROM email_verification; DELETE FROM session; DELETE FROM invitation;
DELETE FROM account_user; DELETE FROM account; DELETE FROM user_identity; DELETE FROM user;

INSERT INTO user (id, email, email_verified, display_name, created_at) VALUES
  ('usr-dev', 'dev@smplkit.test', 1, 'smplkit dev', 1782864000000);
INSERT INTO user_identity (id, user_id, provider, provider_subject, password_hash, created_at) VALUES
  ('d7293504-dbb2-4bda-9fac-4fd50b156364', 'usr-dev', 'PASSWORD', NULL, 'pbkdf2$sha256$210000$1lUJlI1X-TaAVPO7cx9ubg$2p5QBcjLUlfooYHfVdBtDXGT-efILv6JxpocasmfbaM', 1782864000000);

-- The built-in system account (0004 seeds it in prod; the wipe above removes it, so re-create it).
INSERT INTO account (id, key, name, description, created_at, allow_personal_publish) VALUES
  ('acct-system', 'system', 'smplmark', 'Openly licensed benchmark results ingested from third-party sources. Every ingested benchmark credits its source and license, and links back to the original data.', 1782864000000, 0);

-- The dev workspace: personal publish pre-enabled so the whole publish flow is exercisable.
INSERT INTO account (id, key, name, description, created_at, allow_personal_publish) VALUES
  ('acct-smplkit', 'smplkit', 'smplkit', 'smplkit builds developer infrastructure — configuration, feature flags, logging, and audit as independently deployable services.', 1782864000000, 1);
INSERT INTO account_user (account_id, user_id, role, created_at) VALUES
  ('acct-smplkit', 'usr-dev', 'OWNER', 1782864000000);
